/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface STooltip {
        "followMouse": boolean;
        "margin": number;
        "position": 'top' | 'right' | 'bottom' | 'left';
    }
}
declare global {
    interface HTMLSTooltipElement extends Components.STooltip, HTMLStencilElement {
    }
    var HTMLSTooltipElement: {
        prototype: HTMLSTooltipElement;
        new (): HTMLSTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "s-tooltip": HTMLSTooltipElement;
    }
}
declare namespace LocalJSX {
    interface STooltip {
        "followMouse"?: boolean;
        "margin"?: number;
        "position"?: 'top' | 'right' | 'bottom' | 'left';
    }
    interface IntrinsicElements {
        "s-tooltip": STooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "s-tooltip": LocalJSX.STooltip & JSXBase.HTMLAttributes<HTMLSTooltipElement>;
        }
    }
}
